### ISSUE TITLE
This is a different Project

### ISSUE THREAD

**Issue by Tinitto** [mandelashaban593/shoppingList#5]
#### Major Issue
You have created an application that was not asked for. Please refer to the document and follow the instructions step by step
- You were not supposed to have persistent data.
- It was recommended that you use data structures as opposed to a database
- The database was to be used in challenge three that required an API not a website
**Please avoid ignoring instructions**
Here is the [document](https://docs.google.com/document/d/1L0gBhd9Ao0TtTIIX-zEmXzg5zgI7ud9dEwVb4S5dTWw/edit) again. **Refer to it.**

**Comment by mandelashaban593** [comment]
OOOK. Thanks
